# permissions for end users to edit listenercsis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: listenercsi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: listener-operator
    app.kubernetes.io/part-of: listener-operator
    app.kubernetes.io/managed-by: kustomize
  name: listenercsi-editor-role
rules:
- apiGroups:
  - listeners.kubedoop.dev
  resources:
  - listenercsis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - listeners.kubedoop.dev
  resources:
  - listenercsis/status
  verbs:
  - get
