apiVersion: listeners.kubedoop.dev/v1alpha1
kind: ListenerClass
metadata:
  labels:
    app.kubernetes.io/name: listenerclass
    app.kubernetes.io/instance: listenerclass-sample
    app.kubernetes.io/part-of: listener-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: listener-operator
  name: listenerclass-sample
spec:
  serviceType: ClusterIP
---
# Source: listener-operator/templates/listener-classes.yaml
apiVersion: listeners.kubedoop.dev/v1alpha1
kind: ListenerClass
metadata:
  name: cluster-internal
spec:
  serviceType: ClusterIP
---
# Source: listener-operator/templates/listener-classes.yaml
apiVersion: listeners.kubedoop.dev/v1alpha1
kind: ListenerClass
metadata:
  name: external-unstable
spec:
  serviceType: NodePort
---
# Source: listener-operator/templates/listener-classes.yaml
apiVersion: listeners.kubedoop.dev/v1alpha1
kind: ListenerClass
metadata:
  name: external-stable
spec:
  # To support environments that don't have LoadBalancer support, we fall back to using NodePort Services for "stable addresses".
  # To ensure that these addresses are actually stable, the Listener Operator will "bind" such Listeners to only run on the Node that
  # they were originally scheduled to (as controlled by the lifetime of the PersistentVolume). The downside here is that we prevent Kubernetes
  # from migrating that workload to a different Node (such as if it goes down).
  #
  # This is useful for cloud environments with no Cloud Controller Manager (or one which doesn't support LoadBalancers),
  # or on-premise environments that don't support external LoadBalancer peering (such as Calico (https://docs.tigera.io/calico/latest/networking/configuring/advertise-service-ips)
  # or MetalLB (https://metallb.org/)).
  serviceType: NodePort
